{
 "title": "altibaseworkloadlog",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "dbhost",
    "label": "host",
    "query": "node1(105),node2(106),node3(107),node4(108),nval02(receiver),nval03(senderclient),qar5"
   }
  ]
 },
 "panels": [
  {
   "title": "TBS File I/O($dbhost)",
   "type": "graph",
   "description": "Tablespace 별 FILE I/O percentage 를 표시함",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "SYS_TBS_DIS_DATA_IO",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_tbsfileIO_stat",
     "select": [
      [
       { "params": [ "TOTAL_IO_PERCENT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" },
      { "condition": "AND", "key": "TBS_NAME", "operator": "=", "value": "SYS_TBS_DISK_DATA" }
     ]
    },
    {
     "alias": "SYS_TBS_DIS_TEMP_IO",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_tbsfileIO_stat",
     "select": [
      [
       { "params": [ "TOTAL_IO_PERCENT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" },
      { "condition": "AND", "key": "TBS_NAME", "operator": "=", "value": "SYS_TBS_DISK_TEMP" }
     ]
    },
    {
     "alias": "SYS_TBS_DIS_UNDO_IO",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_tbsfileIO_stat",
     "select": [
      [
       { "params": [ "TOTAL_IO_PERCENT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" },
      { "condition": "AND", "key": "TBS_NAME", "operator": "=", "value": "SYS_TBS_DISK_UNDO" }
     ]
    },
    {
     "alias": "USER_DATA_IO",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_tbsfileIO_stat",
     "select": [
      [
       { "params": [ "TOTAL_IO_PERCENT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TBS_NAME", "operator": "=", "value": "QAMS_TBS_DISK_DATA" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Undo Page access state($dbhost)",
   "type": "graph",
   "description": "Undo page read/write",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Undo read",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" },
      { "condition": "AND", "key": "NAME", "operator": "=", "value": "undo page read" }
     ]
    },
    {
     "alias": "Undo write",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" },
      { "condition": "AND", "key": "NAME", "operator": "=", "value": "undo page write" }
     ]
    },
    {
     "alias": "Undo create",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" },
      { "condition": "AND", "key": "NAME", "operator": "=", "value": "undo page create" }
     ]
    }
   ]
  },
  {
   "title": "Data page access stat($dbhost)",
   "type": "graph",
   "description": "Data page 에 대한 read/write count 표시 ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "page read",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" },
      { "condition": "AND", "key": "NAME", "operator": "=", "value": "data page read" }
     ]
    },
    {
     "alias": "page write",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" },
      { "condition": "AND", "key": "NAME", "operator": "=", "value": "data page write" }
     ]
    },
    {
     "alias": "page create",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" },
      { "condition": "AND", "key": "NAME", "operator": "=", "value": "data page create" }
     ]
    }
   ]
  },
  {
   "title": "Record count wrote in Redo Log($dbhost)",
   "type": "graph",
   "description": "Redo log 안에 기록한 record count 의 개수",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Record count",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NAME", "operator": "=", "value": "write redo log count" }
     ]
    }
   ]
  },
  {
   "title": "Redo Log write Bytes($dbhost)",
   "type": "graph",
   "description": "Redo Log 에 기록한 초당 write bytes 의 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "write bytes",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" },
      { "condition": "AND", "key": "NAME", "operator": "=", "value": "write redo log bytes" }
     ]
    }
   ]
  },
  {
   "title": "Redo log count($dbhost)",
   "type": "graph",
   "description": "현재 disk 에 있는 logfile 의 개수 및 log dir 경로 파티셔의 used percentage ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Redolog count",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_diskusage_mycollector",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "LOG_DIR" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    },
    {
     "alias": "Disk used(%)",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_diskusage_mycollector",
     "select": [
      [
       { "params": [ "useratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "LOG_DIR" }
     ]
    }
   ]
  },
  {
   "title": "Undo buffer Pool State($dbhost)",
   "type": "graph",
   "description": "Undo buffer Pool stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "create page count",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_undobuff_stat",
     "select": [
      [
       { "params": [ "CREATE_PAGE_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    },
    {
     "alias": "read page count",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_undobuff_stat",
     "select": [
      [
       { "params": [ "READ_PAGE_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    },
    {
     "alias": "get page count",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_undobuff_stat",
     "select": [
      [
       { "params": [ "GET_PAGE_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    }
   ]
  }
 ]
}