{
 "title": "altibaselock",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "dbhost",
    "label": "host",
    "query": "node1(105),node2(106),node3(107),node4(108),nval02(receiver),nval03(senderclient),qar5"
   }
  ]
 },
 "panels": [
  {
   "title": "Transaction status count($dbhost)",
   "type": "graph",
   "description": "Transaction 상태별 개수 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_tx_count",
     "query": "SELECT mean(\"TRANSACTION_CNT\") FROM \"alti_tx_count\" WHERE (\"TX_STATUS\" = 'TOTAL' AND \"host\" = 'nval02(receiver)') GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "TRANSACTION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TX_STATUS", "operator": "=", "value": "TOTAL" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    },
    {
     "alias": "Begin",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_tx_count",
     "select": [
      [
       { "params": [ "TRANSACTION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TX_STATUS", "operator": "=", "value": "BEGIN" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Lock Aquire count/1m($dbhost)",
   "type": "graph",
   "description": "1분당 Lock Acquire/Release 회수",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Lock Aquire",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NAME", "operator": "=", "value": "lock acquired count" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    },
    {
     "alias": "Lock Release",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NAME", "operator": "=", "value": "lock released count" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Lock count($dbhost)",
   "type": "graph",
   "description": "Lock 개수 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "IX_LOCK",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_locktable_stat",
     "select": [
      [
       { "params": [ "LOCK_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "LOCK_DESC", "operator": "=", "value": "IX_LOCK" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Lock retry /1m($dbhost)",
   "type": "graph",
   "description": "Lock retry 종류별 1분당 발생 건수",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Update retry",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NAME", "operator": "=", "value": "update retry count" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    },
    {
     "alias": "Delete retry",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NAME", "operator": "=", "value": "delete retry count" },
      { "condition": "AND", "key": "NAME", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    },
    {
     "alias": "Lock row retry",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NAME", "operator": "=", "value": "lock row retry count" },
      { "condition": "AND", "key": "NAME", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Altibase Lock List($dbhost)",
   "type": "table",
   "description": "Lock 잡은 Table List ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "alti_lockobj_list",
     "query": "SELECT SID, DB_USERNAME as USERNAME ,TBS_NAME as TABLESPACE,TABLE_NAME,LOCK_DESC from alti_lockobj_list WHERE (\"host\" =~ /^$dbhost$/)",
     "select": [
      [
       { "params": [ "SID" ], "type": "field" }
      ],
      [
       { "params": [ "DB_USERNAME" ], "type": "field" },
       { "params": [ "USERNAME" ], "type": "alias" }
      ],
      [
       { "params": [ "TBS_NAME" ], "type": "field" },
       { "params": [ "TABLESPACE" ], "type": "alias" }
      ],
      [
       { "params": [ "TABLE_NAME" ], "type": "field" }
      ],
      [
       { "params": [ "LOCK_DESC" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$dbhost$/" }
     ]
    }
   ]
  }
 ]
}