{
 "title": "altibaseserver",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Sytem Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU(qar5)",
   "type": "graph",
   "description": "CPU:32Core 1.json 1.sh 2.json 2.sh 3.sh file.sh grafana-6.4.4-1.x86_64.rpm import_bk.sh import.sh influxdb-1.6.1.x86_64.rpm influxdbgrafana_redhat.run influxdbgrafana_ubuntu.run install.sh java java.tar.gz jenkins_root jq odbc.ini odbcinst.ini odbc.tar.gz perf perf_0621 perf_0625 perf_cp perf_edit run_receiver.sh SetEnv set_hdb.env set_Perf.env temp test work 2,Memory:64G",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "cpu(qar5)",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  {
   "title": "System Memory(qar5) ",
   "type": "graph",
   "description": "CPU:32Core 1.json 1.sh 2.json 2.sh 3.sh file.sh grafana-6.4.4-1.x86_64.rpm import_bk.sh import.sh influxdb-1.6.1.x86_64.rpm influxdbgrafana_redhat.run influxdbgrafana_ubuntu.run install.sh java java.tar.gz jenkins_root jq odbc.ini odbcinst.ini odbc.tar.gz perf perf_0621 perf_0625 perf_cp perf_edit run_receiver.sh SetEnv set_hdb.env set_Perf.env temp test work 2,Memory:64G",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mem(qar5)",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  { "title": "Altibase Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "UpTime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "altibase_basic_info",
     "select": [
      [
       { "params": [ "DB_UP_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  {
   "title": "currentSession",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  {
   "title": "DiskBuffHit",
   "type": "singlestat",
   "description": "Disk Buffer Hit 율",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "altibase_buffhit_stat",
     "select": [
      [
       { "params": [ "HIT_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  {
   "title": "PlanCache Hit",
   "type": "singlestat",
   "description": "PlanCache Buffer Hit 율\n",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "altibase_plancache_stat",
     "select": [
      [
       { "params": [ "CACHE_MISS_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used Ratio",
   "type": "gauge",
   "description": "MEM_MAX_DB_SIZE 대비 현재 메모리 space 사용량",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "altibase_mem_stat",
     "select": [
      [
       { "params": [ "MEM_USED_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  {
   "title": "Altibase있는 Filesystem Disk여유율",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "alti_diskusage_mycollector",
     "select": [
      [
       { "params": [ "useratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  {
   "title": "Alti Process CPU usage",
   "type": "graph",
   "description": "Altibase Process 의 CPU 사용량 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "cpu usage",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "altibase" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  {
   "title": "Alti Process Memory Usage",
   "type": "graph",
   "description": "Altibase 메모리 사용량 추이\nRSS:실제 메모리가 세팅된 크기이고 스와핑이 되지 않은 물리적 메모리가 해당 task에 쓰이고 있는 양.\nVMS:가상 메모리의 크기이고,현재 디바이스 메핑에서는 제외 되어 있다는 의미.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RSS",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "altibase" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "qar5" }
     ]
    },
    {
     "alias": "VMS",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_vms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "altibase" }
     ]
    }
   ]
  },
  {
   "title": "Alti Network usage",
   "type": "graph",
   "description": "Altibase 의 초당 Network 사용량 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TcpRecv",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    },
    {
     "alias": "TcpSend",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Altibase Connection 수 추이\n총 접속 및 현재 실행중인 session 수 구분 표시",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "current session",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    },
    {
     "alias": "executing session",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "EXEC_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    },
    {
     "alias": "statement cnt",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "STATEMENT_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  {
   "title": "Service Thread",
   "type": "graph",
   "description": "Altibase Service Thread 개수 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    },
    {
     "alias": "Executing",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "EXECUTE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  },
  {
   "title": "prepare된 statement count",
   "type": "graph",
   "description": "Altibase 의 총 prepare 된 statement(SQL) 의 개수 추이",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "statement count",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NAME", "operator": "=", "value": "prepare success count" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "qar5" }
     ]
    }
   ]
  }
 ]
}